// Beads data fetching hooks

import { useState, useEffect, useCallback } from 'react'
import { useSession } from '../../context/SessionContext'
import type {
  BeadsProject,
  BeadsIssue,
  BeadsIssueDetail,
  BeadsComment,
  TriageResponse,
  InsightsResponse,
  GraphResponse,
  ApiResponse,
} from './types'

const API_BASE = '/api/beads'

// Pattern to match patrol digest titles (auto-generated by witness/deacon)
const PATROL_DIGEST_PATTERN = /^Digest:\s*mol-\w+-patrol$/i

// Filter out patrol digest beads (clutter from routine monitoring)
function filterPatrolDigests(issues: BeadsIssue[], showPatrols: boolean): BeadsIssue[] {
  if (showPatrols) return issues
  return issues.filter(issue => !PATROL_DIGEST_PATTERN.test(issue.title))
}

async function fetchApi<T>(endpoint: string, params?: Record<string, string | string[]>): Promise<ApiResponse<T>> {
  const url = new URL(endpoint, window.location.origin)
  if (params) {
    Object.entries(params).forEach(([key, value]) => {
      if (Array.isArray(value)) {
        value.forEach(item => url.searchParams.append(key, item))
      } else {
        url.searchParams.set(key, value)
      }
    })
  }

  const response = await fetch(url.toString(), { signal: AbortSignal.timeout(10000) })
  return response.json()
}

async function postApi<T>(endpoint: string, body: unknown): Promise<ApiResponse<T>> {
  const response = await fetch(new URL(endpoint, window.location.origin).toString(), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
    signal: AbortSignal.timeout(10000),
  })
  return response.json()
}

interface IssueFetchOptions {
  includeAllStatuses?: boolean
}

function issueListParams(projectPath: string, options?: IssueFetchOptions): Record<string, string> {
  if (!options?.includeAllStatuses) return { path: projectPath }
  return {
    path: projectPath,
    status: 'all',
    limit: '0',
  }
}

// Hook to fetch available projects
export function useProjects() {
  const { settings } = useSession()
  const [projects, setProjects] = useState<BeadsProject[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  const refresh = useCallback(async () => {
    setLoading(true)
    setError(null)
    try {
      // Fetch auto-discovered projects
      const manualPaths = settings.beadsProjectPaths || []
      const result = await fetchApi<{ projects: BeadsProject[] }>(
        `${API_BASE}/projects`,
        manualPaths.length > 0 ? { path: manualPaths } : undefined
      )
      let allProjects: BeadsProject[] = []

      if (result.success && result.data) {
        allProjects = [...result.data.projects]
      }

      setProjects(allProjects)

      if (!result.success && manualPaths.length === 0) {
        setError(result.error?.message || 'Failed to fetch projects')
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Network error')
    } finally {
      setLoading(false)
    }
  }, [settings.beadsProjectPaths])

  useEffect(() => {
    refresh()
  }, [refresh])

  return { projects, loading, error, refresh }
}

// Hook to fetch issues for a project
export function useIssues(projectPath: string | null, showPatrols = false, options?: IssueFetchOptions) {
  const [allIssues, setAllIssues] = useState<BeadsIssue[]>([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const refresh = useCallback(async () => {
    if (!projectPath) {
      setAllIssues([])
      return
    }

    setLoading(true)
    setError(null)
    try {
      const result = await fetchApi<{ issues: BeadsIssue[]; totalCount: number }>(
        `${API_BASE}/issues`,
        issueListParams(projectPath, options)
      )
      if (result.success && result.data) {
        setAllIssues(result.data.issues)
      } else {
        setError(result.error?.message || 'Failed to fetch issues')
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Network error')
    } finally {
      setLoading(false)
    }
  }, [projectPath, options?.includeAllStatuses])

  useEffect(() => {
    refresh()
  }, [refresh])

  // Filter patrol digests based on showPatrols flag
  const issues = filterPatrolDigests(allIssues, showPatrols)

  return { issues, loading, error, refresh }
}

// Hook to fetch triage recommendations
export function useTriage(projectPath: string | null) {
  const [triage, setTriage] = useState<TriageResponse | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const refresh = useCallback(async () => {
    if (!projectPath) {
      setTriage(null)
      return
    }

    setLoading(true)
    setError(null)
    try {
      const result = await fetchApi<TriageResponse>(`${API_BASE}/triage`, { path: projectPath })
      if (result.success && result.data) {
        setTriage(result.data)
      } else {
        setError(result.error?.message || 'Failed to fetch triage')
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Network error')
    } finally {
      setLoading(false)
    }
  }, [projectPath])

  useEffect(() => {
    refresh()
  }, [refresh])

  return { triage, loading, error, refresh }
}

// Hook to fetch insights/metrics
export function useInsights(projectPath: string | null, options?: IssueFetchOptions) {
  const [insights, setInsights] = useState<InsightsResponse | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const refresh = useCallback(async () => {
    if (!projectPath) {
      setInsights(null)
      return
    }

    setLoading(true)
    setError(null)
    try {
      const result = await fetchApi<InsightsResponse>(`${API_BASE}/insights`, issueListParams(projectPath, options))
      if (result.success && result.data) {
        setInsights(result.data)
      } else {
        setError(result.error?.message || 'Failed to fetch insights')
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Network error')
    } finally {
      setLoading(false)
    }
  }, [projectPath, options?.includeAllStatuses])

  useEffect(() => {
    refresh()
  }, [refresh])

  return { insights, loading, error, refresh }
}

// Hook to fetch graph data
export function useGraph(projectPath: string | null) {
  const [graph, setGraph] = useState<GraphResponse | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const refresh = useCallback(async () => {
    if (!projectPath) {
      setGraph(null)
      return
    }

    setLoading(true)
    setError(null)
    try {
      const result = await fetchApi<GraphResponse>(`${API_BASE}/graph`, { path: projectPath })
      if (result.success && result.data) {
        setGraph(result.data)
      } else {
        setError(result.error?.message || 'Failed to fetch graph')
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Network error')
    } finally {
      setLoading(false)
    }
  }, [projectPath])

  useEffect(() => {
    refresh()
  }, [refresh])

  return { graph, loading, error, refresh }
}

export function useIssueDetail(projectPath: string | null, issueId: string | null) {
  const [issue, setIssue] = useState<BeadsIssueDetail | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const refresh = useCallback(async () => {
    if (!projectPath || !issueId) {
      setIssue(null)
      return
    }

    setLoading(true)
    setError(null)
    try {
      const result = await fetchApi<{ issue: BeadsIssueDetail }>(`${API_BASE}/issue`, {
        path: projectPath,
        id: issueId,
      })
      if (result.success && result.data) {
        setIssue(result.data.issue)
      } else {
        setError(result.error?.message || 'Failed to fetch issue detail')
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Network error')
    } finally {
      setLoading(false)
    }
  }, [projectPath, issueId])

  useEffect(() => {
    refresh()
  }, [refresh])

  return { issue, loading, error, refresh }
}

export function useIssueComments(projectPath: string | null, issueId: string | null) {
  const [comments, setComments] = useState<BeadsComment[]>([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const refresh = useCallback(async () => {
    if (!projectPath || !issueId) {
      setComments([])
      return
    }

    setLoading(true)
    setError(null)
    try {
      const result = await fetchApi<{ comments: BeadsComment[] }>(`${API_BASE}/comments`, {
        path: projectPath,
        id: issueId,
      })
      if (result.success && result.data) {
        setComments(result.data.comments)
      } else {
        setError(result.error?.message || 'Failed to fetch comments')
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Network error')
    } finally {
      setLoading(false)
    }
  }, [projectPath, issueId])

  useEffect(() => {
    refresh()
  }, [refresh])

  return { comments, loading, error, refresh }
}

export async function addIssueComment(projectPath: string, issueId: string, comment: string) {
  return postApi<{ comment: BeadsComment }>(`${API_BASE}/comments`, {
    path: projectPath,
    id: issueId,
    comment,
  })
}

// Combined hook for all beads data
export function useBeadsData(projectPath: string | null) {
  const issues = useIssues(projectPath)
  const triage = useTriage(projectPath)
  const insights = useInsights(projectPath)
  const graph = useGraph(projectPath)

  const refreshAll = useCallback(() => {
    issues.refresh()
    triage.refresh()
    insights.refresh()
    graph.refresh()
  }, [issues, triage, insights, graph])

  return {
    issues: issues.issues,
    triage: triage.triage,
    insights: insights.insights,
    graph: graph.graph,
    loading: issues.loading || triage.loading || insights.loading || graph.loading,
    error: issues.error || triage.error || insights.error || graph.error,
    refresh: refreshAll,
  }
}
